name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Build
      run: docker build -t ${{ github.repository }}:latest .

    - name: Authentication Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Проверка наличия существующего образа на Docker Hub
      run: |
        IMAGE_ID=$(docker images -q ${{ github.repository }}:latest)
        if [ ! -z "$IMAGE_ID" ]; then
          echo "Removing an existing image on Docker Hub"
          docker rmi $IMAGE_ID
        else
          echo "Image not found on Docker Hub"
        fi

    - name: Docker Push
      run: docker push ${{ github.repository }}:latest
